#!/bin/bash


getUtil() {
	if [[ "$(id -u)" -eq 0 ]]; then
		echo "Home Space Utilization (All Users)"
		du -sh /home/*
	else
		echo "Home Space Utilization ($USER)"
		du -sh "$HOME"
	fi
}

clear
echo "
Please select:

A. Display System information
B. Display Disk Space
C. Display Home Space Utilization
Q. Quit
"

while true; do
	
read -p "Enter selection [A, B, C or Q] > "

case "$REPLY" in
		q|Q) echo "Program terminated"
			break
		   ;;
		a|A) echo "Hostname $HOSTNAME"
		   uptime
		   ;;
		b|B) df -h
		   ;;
		c|C) getUtil
		   ;;
		*) echo "Invalid entry" >&2
		   exit
		   ;;
esac

done

