#!/bin/bash


# case4-2: test character
# Performing multiple actions


read -n 1 -p "Type a character > "
echo
case "$REPLY" in
	[[:upper:]]) echo "$REPLY is ";;&
[[:upper:]]) echo "$REPLY is upper case";;&
[[:lower:]]) echo "$REPLY is lower case";;&
[[:alpha:]]) echo "$REPLY is alphabetic";;&
[[:digit:]]) echo "$REPLY is digit";;&
[[:graph:]]) echo "$REPLY is visible char";;&
[[:punct:]]) echo "$REPLY is punctuation";;&
[[:space:]]) echo "$REPLY is whitespace";;&
[[:xdigit:]]) echo "$REPLY is hexadecimal";;&
esac
