#!/bin/bash


# Oppgave fra kurs
# Quiz som teller score

quizf() {

	local spm="$1"
	local svar1="$2"
	local svar2="$3"
	local svar3="$4"
	local rsvar="$5"

	if [[ $# -ne 5 ]]; then
		echo "5 params " >&2
		return 1
	fi


	echo
	echo "
		$1
		1) $2
		2) $3
		3) $4
	"

	read -p "Velg svar (1..3) > " svar

	if [[ "$svar" -eq "$rsvar" ]]; then
		echo "Riktig! $svar"
		return 0
	else
		echo "Feil svar, $svar"
		return 1
	fi


}

score=0

quizf "Er dette scriptet kult?" "Ja" "Nei" "Kanskje" "1"
if [[ $? -eq 0 ]]; then
	((score++))
fi

quizf "Hva heter dev. som laget skriptet?" "Sonja" "Kåre" "Anders" "3"
if [[ $? -eq 0 ]]; then
	((score++))
fi

quizf "Er å 'gå' et verb?" "Ja" "Nei" "Vet ikke" "1"
if [[ $? -eq 0 ]]; then
	((score++))
fi

echo "SCORE $score"


