#!/bin/bash

# read-menu: a menu driven system information program

clear
echo "
Please select:

1. Display System information
2. Display Disk Space
3. Display Home Space Utilization
4. Display date
0. Quit
"

CURRENT_TIME="$(date +"%x %r %z")"
read -p "Enter selection [0-4] > "


if [[ "$REPLY" == ^[0-4]$ ]]; then
	echo "Program terminated."
	exit
fi

if [[ "$REPLY" == 1 ]]; then
	echo "Hostname: $HOSTNAME"
	uptime
	exit
fi

if [[ "$REPLY" == 2 ]]; then
	df -h
	exit
fi



if [[ "$REPLY" == 3 ]]; then
	if [[ "$(id -u) -eq 0" ]]; then
		echo "Home Space Utilization (All Users)"
		du -sh /home/*
	else
		echo "Home Space Utilization ($USER)"
		du -sh "$HOME"
	fi
	exit
elif [[ "$REPLY" == 4 ]]; then
	echo "$CURRENT_TIME"
else
	echo "Invalid entry. " >&2
	exit 1
fi

